### ISSUE TITLE
Mark package as abandoned on Packagist

### ISSUE THREAD

**Issue by adamelso** [phpspec/Symfony2Extension#10]
May be useful to mark this package as _abandoned_ now that it is deprecated. In the alternative package field, I guess you can add `phpspec/phpspec` :)

**Comment by stof** [comment]
`phpspec/phpspec` should not be used an alternative package. It does not provide the equivalent feature.
There should be no alternative package given that the recommendation is to not use such feature at all anymore.

**Comment by adamelso** [comment]
@stof I thought specifying an alternative was a requirement? Last time I tried it wouldn't let me

**Comment by adamelso** [comment]
Wait, actually it was me imagining things... the field is optional :) https://github.com/composer/packagist/blob/master/src/Packagist/WebBundle/Form/Type/AbandonedType.php#L37

**Comment by jakzal** [comment]
Great suggestion @adamelso. Done.
